version: 2.1
defaults: &defaults
    working_directory: /tmp/files
    docker:
      - image: cimg/base:current

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
         root: /tmp/files
         paths:
            - .

  build-linux:
    <<: *defaults
    steps:
      - run:
        name: Build Linux
        command: |
            pwd
      - run:
        name: Create Release
        command: |
            pwd

workflows:
  workflow:
    jobs:
      - checkout
      - build-linux:
          requires:
            - checkout