version: 2.1
defaults: &defaults
    working_directory: /tmp/files-bun
    docker:
      - image: cimg/base:current

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls -lart
      - persist_to_workspace:
          root: /tmp/files-bun
          paths:
            - .

  build-linux:
    <<: *defaults
    steps:
      - run: pwd
      - run: ls -lah
      - persist_to_workspace:
          root: /tmp/files-bun
          paths:
            - .

workflows:
  workflow-linux:
    jobs:
      - checkout

      - build-linux:
          requires:
            - checkout